### ISSUE TITLE
RG-62 Subscription is not deleted from the database when error and user got deleted

### ISSUE THREAD

**Issue by richmish58** [vineetsaurabh/rolaguru#122] opened 2018-07-20 07:22 UTC
*Steps To Reproduce:*

1. Create Flexcube error
2. Subscribe it
3. check the database with below query 
mysql> select * from flexerror_subscribe;
4.  Now delete it from UI

Current Behavior: Subscriptions not deleting from database.

**Comment by vineetsaurabh** [comment] 2018-07-27 06:53
not a bug. It was testing with old data, while db model was changed.

**Comment by vineetsaurabh** [comment] 2018-08-07 18:07
Fixed with RG-56

**Closed by vineetsaurabh** 2018-08-07 18:07 UTC
Labels: bug
